### PR TITLE
Grails 3.2.11/JDK8/ala-bootstrap3 upgrade

### PR DESCRIPTION
**Pull request by charvolant**
Also includes fixes for https://github.com/AtlasOfLivingAustralia/bie-index/issues/151 and https://github.com/AtlasOfLivingAustralia/bie-index/issues/149

### CODE REVIEW

**Comment by nickdos** [comment]
Build failed... is that a problem?

**Comment by charvolant** [comment]
Why yes, yes it is. Interesting.

**Comment by charvolant** [comment]
Finally mergeable with fixes to build configuration

**Comment by charvolant** [comment]
Now with conversion to grails 3.2.11

**Comment by nickdos** [comment]
Could you re-submit this PR to merge into grails3 branch instead of master, pls?

**Pull request closed without merging**
