### PR TITLE
Updated translations, linkIdentifier fix

### PR DESCRIPTION
**Pull request by charvolant**

### CODE REVIEW

**Comment by Rita-C** [comment]
@charvolant , can I test this fix somewhere? 
can https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/199 be tested?

**Comment by charvolant** [comment]
One way of testing this is to run it locally with either a local version of solr or link it to the bie-ws-test solr instance via ssh. If the latter, you'll need to add the linkText field to the solr schema. I can do that for you.

**Comment by Rita-C** [comment]
> One way of testing this is to run it locally with either a local version of solr or link it to the bie-ws-test solr instance via ssh. If the latter, you'll need to add the linkText field to the solr schema. I can do that for you.

**Comment by Rita-C** [comment]
Okay, code changes look good, will test https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/199 once code released.

**Pull request merged**
